try{
  let a = 2 + b
}catch(e){
  console.log("deu errado por que: " + e)
}